"""Generated by tools/update_versions.sh — do not edit by hand.

Schema:

    HELM_VERSIONS = {
        "<version>": {
            "<platform>": {
                "url":    "https://get.helm.sh/helm-v<version>-<plat>.tar.gz",
                "sha256": "<sha256>",
            },
            ...
        },
    }

Maintainer flow:
    bash tools/update_versions.sh <version>            # add or update
    bash tools/update_versions.sh <version> --update   # also auto-edit

Asset shape: Helm publishes per-platform tarballs at
    https://get.helm.sh/helm-v<ver>-<plat>.tar.gz
Each tarball extracts to `<plat>/helm` plus license + README. The
repository rule extracts the tarball and re-exposes the binary at the
top-level path `helm` so the toolchain wiring is symmetric across
platforms.
"""

HELM_VERSIONS = {
    "3.20.2": {
        "linux_amd64": {
            "url":    "https://get.helm.sh/helm-v3.20.2-linux-amd64.tar.gz",
            "sha256": "258e830a9e613c8a7a302d6059b4bb3b9758f2f3e1bb8ea0d707ce10a9a72fea",
            "strip":  "linux-amd64",
        },
        "darwin_amd64": {
            "url":    "https://get.helm.sh/helm-v3.20.2-darwin-amd64.tar.gz",
            "sha256": "7de04301f28b902a74f6286ed941cadc86ee5e6a9086a18f2ccf1f548e99d618",
            "strip":  "darwin-amd64",
        },
        "darwin_arm64": {
            "url":    "https://get.helm.sh/helm-v3.20.2-darwin-arm64.tar.gz",
            "sha256": "139c794c22f16b579d08ddd3008c8038b9bb2814f35b5bcca91f50a1f458978d",
            "strip":  "darwin-arm64",
        },
    },
}

PLATFORMS = {
    "linux_amd64":  ["@platforms//os:linux", "@platforms//cpu:x86_64"],
    "darwin_amd64": ["@platforms//os:osx",   "@platforms//cpu:x86_64"],
    "darwin_arm64": ["@platforms//os:osx",   "@platforms//cpu:arm64"],
}
